apiVersion: v1
kind: Pod
metadata:
  name: pod-with-liveness-check
spec:
  containers:
    - image: k8spatterns/random-generator:1.0
      name: random-generator
      env:
        - name: DELAY_STARTUP
          value: "20"
      ports:
        - containerPort: 8080
      livenessProbe: # config Liveness Probe
        httpGet: # using http method
          path: / # path to exec http check
          port: 8080 # port
        initialDelaySeconds: 30 # deplay 30s before check