apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readiness-check
spec:
  containers:
    - image: k8spatterns/random-generator:1.0
      name: random-generator
      readinessProbe: # config Readiness Probe
        exec: # using exec method
          command: [ "stat", "/var/run/random-generator-ready" ]