#chi ho tro cac nen tang cloud
# -------------------------------------------------------------------------------
#Ta dùng câu lệnh sau để tạo một Persistent Disk trên google cloud:
# gcloud compute disks create --size=1GiB --zone=europe-west1-b mongodb
# -------------------------------------------------------------------------------
# Use this command to create cloud volume:
# kubectl create -f gcepd.yaml
# -------------------------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - image: mongo
      name: mongodb
      ports:
        - containerPort: 27017
          protocol: TCP
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumes:
    - name: mongodb-data
      gcePersistentDisk: # google cloud disk volume
        pdName: mongodb # name of the persistent disk on google cloud
        fsType: ext4
# an alternative cloud storage:
  # volumes:
  #     - name: mongodb-data
  #       awsElasticBlockStore: # using AWS ElasticBlockStore instead of gcePersistentDisk
  #         pdName: aws-ebs # name of the EBS on AWS
  #         fsType: ext4
