#check if this work:
# kubectl apply -f emptydir.yaml
# kubectl port-forward fortune 8080:80
# curl http://localhost:8080
# --------------------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - name: html-generator
      image: luksa/fortune
      volumeMounts:
        - name: html # The volume called html is mounted at /var/htdocs in the container
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html # The volume called html is mounted at /usr/share/nginx/html in the container
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes: # define volumes
    - name: html # name of the volumes
      emptyDir: {} # define type is emptyDir

# image content :
# #!/bin/bash
# trap "exit" SIGINT
# mkdir /var/htdocs

# while :
# do
#   echo $(date) Writing fortune to /var/htdocs/index.html
#   /usr/games/fortune > /var/htdocs/index.html
#   sleep 10
# done
