apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: fast # This PVC use fast StorageClass
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
# ---------------------COMMAND SEESION---------------------------------------------------------
# kubectl get sc
# ----------------------Sample result--------------------------------
# NAME                TYPE
# fast                kubernetes.io/gce-pd
# standard (default)  kubernetes.io/gce-pd