apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: hello-app
spec:
  # provide revision with the amount you want
  # revisionHistoryLimit: 1
  replicas: 3
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: 080196/hello-app:v1
        name: hello-app
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000

# image content:
# const http = require("http");

# const server = http.createServer((req, res) => {
#   res.end("Hello application v1\n")
# });

# server.listen(3000, () => {
#   console.log("Server listen on port 3000")
# })