apiVersion: v1
kind: Pod
metadata:
  name:  pod-privileged
spec:
  containers:
    - name: main
      image: alpine
      command: ["/bin/sleep", "999999"]
      securityContext:
        privileged: true
# ------------------------------ALTERNATIVE WAY------------------------------
      # securityContext:
      #         capabilities: # Capabilities are added or dropped under the securityContext property.
      #           add: # use add
      #             - SYS_TIME # add the SYS_TIME capability.
# ========================Chan process ghi de len filesystem=========================
      # securityContext:
      #         readOnlyRootFilesystem: true # This container’s filesystem can’t be written to